[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Civil Registration and Vital Statistics"
authors = [{name = "Ibukunoluwa Omonijo", email = "ibukun.omonijo@nationalpopulation.gov.ng"}]
dynamic = ["version", "description"]
